2024-04-10 20:42:19,182 INFO: Microblog startup [in D:\microblog\app\__init__.py:46]
2024-04-10 20:50:40,715 INFO: Microblog startup [in D:\microblog\app\__init__.py:46]
2024-04-10 20:53:18,321 INFO: Microblog startup [in D:\microblog\app\__init__.py:46]
2024-04-10 20:54:58,602 INFO: Microblog startup [in D:\microblog\app\__init__.py:46]
2024-04-11 10:29:41,298 INFO: Microblog startup [in D:\microblog\app\__init__.py:48]
2024-04-11 10:29:45,129 ERROR: Exception on /login [GET] [in D:\microblog\venv\lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\microblog\app\routes.py", line 41, in login
    return render_template('login.html',title='Sign in',form=form)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2024-04-11 10:30:20,421 INFO: Microblog startup [in D:\microblog\app\__init__.py:48]
2024-04-11 10:30:23,691 ERROR: Exception on /login [GET] [in D:\microblog\venv\lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\microblog\app\routes.py", line 41, in login
    return render_template('login.html',title='Sign in',form=form)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2024-04-11 10:38:33,504 INFO: Microblog startup [in D:\microblog\app\__init__.py:48]
2024-04-11 11:15:48,105 INFO: Microblog startup [in D:\microblog\app\__init__.py:48]
2024-04-11 11:16:18,489 ERROR: Exception on /user/Vadiraj [GET] [in D:\microblog\venv\lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\microblog\app\routes.py", line 72, in user
    return render_template('user.html',user=user,posts=posts,form=form,next_url=next_url,prev_url=prev_url)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\microblog\app\templates\base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "D:\microblog\app\templates\user.html", line 11, in block 'content'
    <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
  File "D:\microblog\venv\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followers_count'
2024-04-11 11:25:56,001 INFO: Microblog startup [in D:\microblog\app\__init__.py:48]
2024-04-11 11:26:00,101 ERROR: Exception on /user/Vadiraj [GET] [in D:\microblog\venv\lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\microblog\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\microblog\app\routes.py", line 72, in user
    return render_template('user.html',user=user,posts=posts,form=form,next_url=next_url,prev_url=prev_url)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\microblog\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\microblog\app\templates\base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "D:\microblog\app\templates\user.html", line 11, in block 'content'
    <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
  File "D:\microblog\venv\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'following_count'
